import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DRS Zone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} antialiased bg-blackfundo`}>
        <main className="p-2 lg:p-4 flex flex-col lg:flex-row">
          <div className="flex flex-col lg:flex-row w-full">
            <Sidebar/>
            <div className="w-full">
              {children}
            </div>
          </div>   
        </main>
      </body>
    </html>
  );
}
